package com.elpisor.hq.api_controllers;

public enum Errors {
    NO_ERRORS, EMAIL_ALREADY_EXISTS, PHONE_ALREADY_EXISTS, SKILL_ALREADY_EXISTS, REGION_ALREADY_EXISTS,
    WRONG_EMAIL, WRONG_PHONE, WRONG_NAME_LENGTH, WRONG_USERNAME_LENGTH, WRONG_SURNAME_LENGTH,
    DATA_INCOMPLETE, BAD_PASSWORD, ID_NOT_REGISTERED, PHONE__NOT_REGISTERED, EMAIL_NOT_REGISTERED,
    SKILL_NOT_FOUND_IN_USER_PROFILE, MISSING_VALUE_TIMEZONE, WRONG_FORMAT_TIMEZONE,
    NUMBER_OF_TIMES_NOT_EVEN, WRONG_TIME_FORMAT, WRONG_TIME_ORDER, ACCOUNT_DISABLED
}
